language: crystal
sudo: required
addons:
  postgresql: "9.6"
services:
  - postgresql
env:
  - HORNET_ENV=test HORNET_DB_URL=postgres://postgres@localhost:5432/hornet_test
script:
  - bash .travis/install-postgres-10.sh
  - psql -c 'create database hornet_test;' -U postgres
  - crystal tool format --check src spec db
  - crystal spec
  - shards build hornet --no-codegen
